# gjed Public Repository Configurations
# Public/OSS repositories managed by gjed organization
#
# These repositories use the gjed + oss groups for configuration.

# GitHub Profile

# https://github.com/gjed/gjed
gjed:
  description: "Config files for my GitHub profile."
  groups: ["gjed", "oss"]
  topics:
    - github

# OSS Projects

# https://github.com/gjed/fosdem-video-downloader
fosdem-video-downloader:
  description: "A tool to download videos from FOSDEM"
  groups: ["gjed", "oss"]
  topics:
    - fosdem
    - jellyfin
    - downloader
    - python

# https://github.com/gjed/jenkins-opentelemetry-dashboards
jenkins-opentelemetry-dashboards:
  description: "OpenTelemetry dashboards for Jenkins monitoring"
  groups: ["gjed", "oss"]
  license: "apache-2.0"
  topics:
    - jenkins
    - opentelemetry
    - grafana

# https://github.com/gjed/terraform-github-config-as-yaml
terraform-github-config-as-yaml:
  description: "Github repository configurations managed via YAML"
  groups: ["gjed", "oss", "dependabot"]
  topics:
    - github
    - terraform

# https://github.com/gjed/github-configs-public
github-configs-public:
  description: "Github repository configurations managed via YAML"
  groups: ["gjed", "oss", "dependabot"]
  topics:
    - github
    - terraform

# https://github.com/gjed/whisperx-api-server
whisperx-api-server:
  description: "FastAPI server for WhisperX transcription library"
  groups: ["gjed", "oss", "dependabot"]
  topics:
    - github
    - whisperx

# https://github.com/gjed/sinapsi-converter
sinapsi-converter:
  description: "Simple tool to convert Sinapsi CSV to XLSX files"
  groups: ["gjed", "oss", "dependabot"]
  topics:
    - github
    - sinapsi

# https://github.com/gjed/siemens-converter
siemens-converter:
  description: "Simple tool to convert siemens CSV to XLSX files"
  groups: ["gjed", "oss", "dependabot"]
  topics:
    - github
    - siemens

# https://github.com/gjed/workshop-2026-k8s
workshop-2026-k8s:
  description: "Kubernetes workshop for 2026 IDI Devops Bologna"
  groups: ["gjed", "oss", "dependabot"]
  topics:
    - github
    - kubernetes

