# OSS Projects
# Open source tools, infrastructure projects, and conference demos

# https://github.com/gjed/fosdem-video-downloader
fosdem-video-downloader:
  description: "A tool to download videos from FOSDEM"
  groups: ["gjed", "oss"]
  topics:
    - fosdem
    - jellyfin
    - downloader
    - python

# https://github.com/gjed/jenkins-opentelemetry-dashboards
jenkins-opentelemetry-dashboards:
  description: "OpenTelemetry dashboards for Jenkins monitoring"
  groups: ["gjed", "oss"]
  license: "apache-2.0"
  topics:
    - jenkins
    - opentelemetry
    - grafana

# https://github.com/gjed/terraform-github-config-as-yaml
terraform-github-config-as-yaml:
  description: "Github repository configurations managed via YAML"
  groups: ["gjed", "oss"]
  homepage_url: "https://registry.terraform.io/modules/gjed/config-as-yaml/github/latest"
  topics:
    - github
    - terraform

# https://github.com/gjed/github-configs-public
github-configs-public:
  description: "Github repository configurations managed via YAML"
  groups: ["gjed", "oss"]
  topics:
    - github
    - terraform

# https://github.com/gjed/demo-otel-weaver
demo-otel-weaver:
  description: "Demo for OpenTelemetry Weaver talk"
  groups: ["gjed", "oss"]
  topics:
    - github
    - opentelemetry
    - weaver
    - demo

# https://github.com/gjed/renovate-exporter
renovate-exporter:
  description: "OpenTelemetry exporter for GitHub Renovate"
  groups: ["gjed", "oss"]
  topics:
    - renovate
    - opentelemetry
    - exporter

